name: Rust Test On matrix toolchain * os

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain'
        required: false
        type: string
        default: '["stable"]'
      os:
        description: 'OS'
        required: false
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      fail-fast:
        description: 'Fail fast'
        required: false
        type: boolean
        default: true
      maturin-prj-dir:
        description: 'Maturin project directory'
        required: false
        type: string
        default: '.'
    
jobs:
  test:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        toolchain: ${{ fromJson( inputs.toolchain ) }}
        os: ${{ fromJson( inputs.os ) }}
        
    name: test ${{ matrix.os }}/${{ matrix.toolchain }} 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build_env
          init-shell: bash zsh powershell
          create-args: >-
            maturin
            pytest
      - name: Test with-in micromamba environment
        run: |
          micromamba env list &&
          env &&
          cargo nextest run --all-features &&
          cargo nextest run --examples --all-features
          cargo test --doc --all-features
          cargo doc --no-deps --all-features
          pushd ${{ inputs.maturin-prj-dir }}
          maturin develop
          pytest
  
