name: Wheel + Pytest matrix Python version

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        type: string
        default: '["3.11", "3.12"]'
      os:
        description: 'OS'
        required: false
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      fail-fast:
        description: 'Fail fast'
        required: false
        type: boolean
        default: true
      pyproject-toml-dir:
        description: 'Directory contains pyproject.toml file'
        required: false
        type: string
        default: '.'
    
jobs:
  test:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        python-version: ${{ fromJson( inputs.python-version ) }}
        os: ${{ fromJson( inputs.os ) }}
        
    name: test ${{ matrix.os }}/${{ matrix.python-version }} 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}      
      - name: Install tox and its dependencies
        run: pip install tox pytest-cov pytest-mock pytest-sugar
      - name: Test
        run: tox run --colored=yes
