name: Rust Test On matrix toolchain * os

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain'
        required: false
        type: string
        default: '["stable", "nightly"]'
      os:
        description: 'OS'
        required: false
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      fail-fast:
        description: 'Fail fast'
        required: false
        type: boolean
        default: true
    
jobs:
  test:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        toolchain: ${{ fromJson( inputs.toolchain ) }}
        os: ${{ fromJson( inputs.os ) }}
        
    name: test ${{ matrix.os }}/${{ matrix.toolchain }} 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: |
          cargo nextest run --all-features
          cargo nextest run --examples --all-features
          cargo test --doc --all-features
          cargo --config 'env.RUSTDOCFLAGS="-D warnings"' doc --all-features
          cargo clippy --all-features -- --deny warnings
