name: Rust Test On matrix toolchain * os

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain'
        required: false
        type: string
        default: '["stable", "nightly"]'
      os:
        description: 'OS'
        required: false
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      fail-fast:
        description: 'Fail fast'
        required: false
        type: boolean
        default: true
      micromamba-env-file:
        description: 'Create micromamba environment'
        required: false
        type: string
        default: 'NONE'
    
jobs:
  test:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        toolchain: ${{ fromJson( inputs.toolchain ) }}
        os: ${{ fromJson( inputs.os ) }}
        
    name: test ${{ matrix.os }}/${{ matrix.toolchain }} 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash zsh powershell
        if: ${{ inputs.micromamba-env-file != 'NONE' }}
      - name: Test tests
        run: cargo nextest run --all-features
      - name: Test examples
        run: cargo nextest run --examples --all-features
      - name: Test docs
        run: cargo test --doc --all-features
      - name: Test doc creation
        run: cargo doc --no-deps --all-features
