name: Rust Clippy

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'The Rust toolchain to use'
        required: false
        type: string
        default: 'stable'
    

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          override: true
          components: clippy