name: Rust Bench matrix [ubuntu-latest, windows-latest, macos-latest] with inputs.toolchain = stable

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'Rust toolchain'
        required: false
        type: string
        default: '["stable"]'
      os:
        description: 'OS'
        required: false
        type: string
        default: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      fail-fast:
        description: 'Fail fast'
        required: false
        type: boolean
        default: true
      with-python-version:
        description: 'Install python with given version, if value not provided, it will not install python'
        required: false
        type: string
        default: ''


jobs:
  bench:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        toolchain: ${{ fromJson( inputs.toolchain ) }}
        os: ${{ fromJson( inputs.os) }}
        
    name: bench ${{ matrix.os }}/${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        if: ${{ inputs.with-python-version != '' }}
        with:
          python-version: ${{ inputs.with-python-version }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@nextest
      - name: Bench
        run: |
          cargo bench --all-features

        
