name: Rust Test on choosen OS and toolchain

on:
  workflow_call:
    inputs:
      toolchain:
        description: 'The toolchain to use for testing'
        required: true
        type: string
      os:
        description: 'The OS to use for testing'
        required: true
        type: string

jobs:
  test:
      runs-on: ${{ inputs.os }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: ${{ inputs.toolchain }}
            override: true
        - uses: taiki-e/install-action@nextest
        - name: Test
          run: |
            cargo nextest run --all-features
            cargo nextest run --examples --all-features
            cargo test --doc --all-features
            cargo doc --all-features

